require 'packages'
require 'options'
require 'keymaps'
require 'colorscheme'
require 'lsp'
require 'nvim-treeConfig'
require 'treesitterConfig'
require 'telescopeConfig'
require 'toggletermConfig'
require 'virt-columnConfig'
require 'gitsignsConfig'
require 'fidgetConfig'
require 'autopairsConfig'
require 'illuminateConfig'
require 'dapConfig'
require 'orgmodeConfig'
require 'refactor'
require 'homescreen'
require 'codeActions'
require 'completion'
require 'ai'

function DUMP(tbl)
  vim.api.nvim_echo({ { vim.inspect(tbl) } }, true, {})
end
